version: '3.1'

services:
  postgres:
    image: postgres
    ports:
    - 5432:5432

    environment:
    - POSTGRES_DB=job_scheduler
    - POSTGRES_USER=job_scheduler
    - POSTGRES_PASSWORD=job_scheduler
