spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres/job_scheduler}
    username: ${DB_USER:job_scheduler}
    password: ${DB_PASSWORD:job_scheduler}

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
